---
title: "Project2"
author: "Yinzhou Zhu"
date: "6/29/2020"
output: github_document
params:
  day_of_week: "monday"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(knitr)
library(caret)
library(gbm)
library(GGally)
library(parallel)
library(doParallel)
library(rmarkdown)
```

```{r functions}
convert_to_factors <- function(column_list) {
  popularity_data[column_list] <- lapply(popularity_data[column_list], factor)
  return(popularity_data)
}
filter_by_day <- function(day){
  day_data <- popularity_data %>% filter(select(popularity_data, contains(day))==1) %>% select(!contains("week") & !url & !timedelta)
  return(day_data)
}
scatter_plots <- function(var_1, var_2) {
  base_plot <-ggplot(daily_data, aes(remove_outliers(.data[[var_1]]), remove_outliers(.data[[var_2]]))) + geom_point()
  base_plot + geom_smooth()
}
box_plots <- function(var_1, var_2){
  base_plot <-ggplot(daily_data, aes(.data[[var_1]], remove_outliers(.data[[var_2]]))) 
  base_plot + geom_boxplot(outlier.shape = NA) + geom_jitter(size = 0.2, width = 0.3, aes(colour = .data[[var_1]]))
}
bar_plots <- function(var_1) {
  base_plot <-ggplot(daily_data, aes(remove_outliers(.data[[var_1]])))
  base_plot + geom_bar()
}
corr_plots <- function(columns){
  corr_plot <- ggpairs(daily_data, columns = columns, axisLabels = "none",
          upper = list(continuous = wrap("cor", size = 1.5)))
  print(corr_plot + theme(strip.placement = "outside", text = element_text(size = 5)))
}
remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  y
}
```

```{r data parsing and inspection}
popularity_data <- read.csv("OnlineNewsPopularity.csv")
anyNA(popularity_data)
popularity_data <- convert_to_factors(c("data_channel_is_lifestyle", "data_channel_is_entertainment", "data_channel_is_bus", "data_channel_is_socmed", "data_channel_is_tech", "data_channel_is_world"))
str(popularity_data)
```

```{r data partition}
daily_data <- filter_by_day(params$day_of_week)
set.seed(35)
partition_index <- createDataPartition(daily_data$shares,
              p = .8,
              list = FALSE,
              times = 1)
partition_index <- as.vector(partition_index)
train_data <- daily_data[partition_index, ]
test_data <- daily_data[-partition_index, ]
```

```{r initial data exploration}
scatter_plots("global_rate_positive_words", "shares")
scatter_plots("global_rate_negative_words", "shares")
scatter_plots("global_sentiment_polarity", "shares")
box_plots("data_channel_is_lifestyle", "shares")
box_plots("data_channel_is_entertainment", "shares")
box_plots("data_channel_is_bus", "shares")
box_plots("data_channel_is_socmed", "shares")
box_plots("data_channel_is_tech", "shares")
box_plots("data_channel_is_world", "shares")
scatter_plots("n_unique_tokens", "shares")
corr_plots(c("LDA_00", "LDA_01", "LDA_02", "LDA_03", "LDA_04"))
scatter_plots("kw_avg_avg", "shares")
```

```{r linear model}
linear_fit <- lm(shares ~ kw_avg_avg + n_tokens_title + num_keywords + self_reference_avg_sharess,
       data = train_data)
linear_pred <- predict(linear_fit, newdata = test_data)
summary(linear_fit)$adj.r.squared
```
```{r non-linear models}
# cores <- 6
# cl <- makePSOCKcluster(cores)
# registerDoParallel(cl)
# training_control <- trainControl(method = "repeatedcv", number = 10, repeats = 3, verboseIter = FALSE, allowParallel = TRUE)
# set.seed(333)
# rf_fit <- train(shares ~ ., train_data, method = "rf",
#                 preProcess=c("center", "scale"), trControl = training_control)
# rf_fit
# rf_pred <- predict(rf_fit, newdata = select(test_data, -"shares"))
# 
# set.seed(333)
# tree_bag_fit <- train(shares ~ ., train_data, method = "treebag", 
#                  preProcess=c("center", "scale"), trControl = training_control)
# tree_bag_fit
# bagged_pred <- predict(tree_bag_fit, newdata = select(test_data, -"shares"))
# 
# set.seed(333)
# bt_fit <- train(shares ~ ., train_data, method = "gbm", verbose = 0,
#                 preProcess=c("center", "scale"), trControl = training_control,
#                 tuneGrid = expand.grid(n.trees = c(100, 200, 500), interaction.depth = c(1,4,9),
#                                        shrinkage = 0.1, n.minobsinnode = 10))
# bt_fit
# bt_pred <- predict(bt_fit, newdata = select(test_data, -"shares"))
# 
# 
# stopCluster(cl)
# registerDoSEQ()
```

```{r automation, results='hide', echo=TRUE}
days <- c("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday")

map(.x = days, .f = ~render(input = "template.Rmd", 
                            output_file = paste0(.x,"report.md"), 
                            params = list(day_of_week = .x))
    )
```
